# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alg_cart',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20)),
                ('smallsrc', models.CharField(max_length=200)),
                ('bigsrc1', models.CharField(max_length=200)),
                ('xxsrc1', models.CharField(max_length=200)),
                ('bigsrc2', models.CharField(max_length=200)),
                ('xxsrc2', models.CharField(max_length=200)),
                ('bigsrc3', models.CharField(max_length=200)),
                ('xxsrc3', models.CharField(max_length=200)),
                ('bigsrc4', models.CharField(max_length=200)),
                ('xxsrc4', models.CharField(max_length=200)),
                ('bigsrc5', models.CharField(max_length=200)),
                ('xxsrc5', models.CharField(max_length=200)),
                ('productlongname', models.CharField(max_length=256)),
                ('msg', models.CharField(max_length=256)),
                ('salemsg', models.CharField(max_length=256)),
                ('news', models.CharField(max_length=256)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remnum', models.IntegerField()),
                ('num', models.IntegerField()),
                ('dealerid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'alg_goods',
            },
        ),
        migrations.CreateModel(
            name='New_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'alg_new_goods',
            },
        ),
        migrations.CreateModel(
            name='New_goods_brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'alg_new_goods_brand',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'alg_user',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'alg_wheel',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
