# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-15 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='alg_user',
        ),
    ]
